version: '3'
services:
  netdata:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - httpd-log:/usr/local/apache2/logs:ro
    depends_on:
      - springboot2
      - httpd

  springboot2:
    build: mocks/springboot2
    ports:
      - 8080:8080

  httpd:
    image: httpd:2.4
    volumes:
      - ./mocks/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
      - httpd-log:/usr/local/apache2/logs:rw

  blackbox_probe:
    image: alpine
    depends_on:
      - springboot2
      - httpd
    command:
      - '/bin/sh'
      - '-c'
      - |
        while :; do
          wget -O /dev/null http://springboot2:8080/hello || :
          wget -O /dev/null http://springboot2:8080/hello || :
          wget -O /dev/null http://springboot2:8080/ || :
          wget -O /dev/null http://httpd/ || :
          wget -O /dev/null http://httpd/not_exist || :
          sleep 0.7
        done

volumes:
  httpd-log:
