version: '3'
services:
  netdata:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    depends_on:
      - springboot2
  springboot2:
    build: mocks/springboot2
    ports:
      - 8080:8080
  nginx:
    build: mocks/nginx
    ports:
      - 8000:80
  springboot2_random:
    image: alpine
    depends_on:
      - springboot2
      - nginx
    command:
      - '/bin/sh'
      - '-c'
      - |
        function httpget() {
            while :; do
                echo wget $$1
                wget -O /dev/null $$1 2>&1 || :
                sleep $$2
            done
        }

        trap 'kill $$(jobs -pr)' SIGINT SIGTERM EXIT

        httpget http://springboot2:8080/hello 0.5 &
        httpget http://springboot2:8080 1 &
        httpget http://nginx/empty_gif 0.3 &
        httpget http://nginx/ 0.5 &

        while true; do sleep 86400; done